@extends('layouts.default')

@section('content')

<h2>Ajouter un rendez-vous</h2>
<form action="{{ route('appointment.store') }}" method="POST">
    @csrf
    <p class="text-danger"><i>* Champs obligatoires</i></p>
    <div class="row my-5">
        <div class="col-md-12">
            <label for="birthdate">Date de naissance du patient:<span class="text-danger"> *</span></label>
            <input type="date" id="birthdate" class="form-control @error('birthdate') is-invalid @enderror" name="birthdate" value="{{ old('birthdate') }}" required>
        </div>
        <div class="col-md-6">
            <label for="lastname" class="mdb-main-label">Nom de famille du patient: <span class="text-danger">*</span></label>
            <select id="lastname" class="form-control @error('lastname') is-invalid @enderror" name="lastname" data-live-search="true" required>
                <option value="" disabled selected>Inscrivez d'abord une date de naissance</option>
                <!-- Generated by Ajax -->
            </select>
        </div>
        <div class="col-md-6">
            <label for="firstname" class="mdb-main-label">Prénom du patient: <span class="text-danger">*</span></label>
            <select id="firstname" class="form-control @error('firstname') is-invalid @enderror" name="firstname" required>
                <option value="" disabled selected>Sélectionnez d'abord le nom de famille du patient</option>
                <!-- Generated by Ajax -->
            </select>
        </div>
    </div>
    <hr>
    <div class="row my-5">
        <div class="col-md-6">
            <label for="exam" class="mdb-main-label">Type d'examen: <span class="text-danger">*</span></label>
            <select id="exam" class="form-control @error('exam') is-invalid @enderror" name="exam" required>
                @foreach($exams as $exam)
                <option value="{{ $exam->id }}">{{ $exam->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-6">
            <label for="urgency" class="mdb-main-label">Urgence: <span class="text-danger">*</span></label>
            <select id="urgency" class="form-control @error('urgency') is-invalid @enderror" name="urgency" required>
                <option value="" disabled selected>Sélectionnez l'urgence de l'examen</option>
                @foreach($urgencies as $urgency)
                <option value="{{ $urgency }}">{{ $urgency }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-md-6">
            <label for="hospital" class="mdb-main-label">Hopital: <span class="text-danger">*</span></label>
            <select id="hospital" class="form-control @error('hospital') is-invalid @enderror" name="hospital" required>
                @foreach($hospitals as $hospital)
                <option value="{{ $hospital->id }}">{{ $hospital->name }}</option>
                @endforeach
            </select>
        </div>
        <div id="firstFreeSlot" class="col-md-12 my-3">
        </div>
    </div>
    <hr>
    <div class="row my-4">
        <div class="col-lg-12">
            <label for="comment">Commentaire évententuel:</label>
            <textarea id="comment" name="comment" class="form-control" rows="2">{{ old('comment') }}</textarea>
        </div>
    </div>

    <button type="submit" class="btn btn-primary btn-rounded waves-effect mt-5 float-right">Ajouter</button>
</form>

<script>
// Generate lastnames which matchs with the birthdate
    $(document).ready(function () {
        $('#birthdate').change(function () {
            if ($('#birthdate').val !== '') {
                var value = $(this).val();
                $.ajax({
                    url: "/fetchLastname",
                    method: "GET",
                    data: {value: value},
                    success: function (result) {
                        $('#lastname').html(result);
                    }
                })
            }
        });
        $('#lastname').change(function () {
            if ($('#lastname').val !== '') {
                var value = $(this).val();
                $.ajax({
                    url: "/fetchFirstname",
                    method: "GET",
                    data: {value: value},
                    success: function (result) {
                        $('#firstname').html(result);
                    }
                })
            }
        });
        $('#urgency').change(function () {
            if ($('#urgency').val !== '') {
                var value = $(this).val();
                $.ajax({
                    url: "/ajaxFindAFreeSlot",
                    method: "GET",
                    data: {urgency: value},
                    success: function (result) {
                        $('#firstFreeSlot').html(result);
                    }
                })
            }
        });
        $(document).on("click", '#newDate', function() { 
            console.log('click pris en compte');
            if ($('#urgency').val !== '') {
                var valueUrgency = $("#urgency").val();
                var valueDate = $("#date").val();
                $.ajax({
                    url: "/ajaxFindAFreeSlot",
                    method: "GET",
                    data: {
                        urgency: valueUrgency,
                        currentDate: valueDate
                    },
                    success: function (result) {
                        $('#firstFreeSlot').html(result);
                    }
                })
            }
        });
    });
</script>

@endsection