@extends('layouts.default')

@section('content')

<h2>Ajouter un rendez-vous</h2>
<form action="{{ route('appointment.store') }}" method="POST">
    @csrf
    <p class="text-danger"><i>* Champs obligatoires</i></p>
    <div class="row">
        <div class="col-md-12">
            <label for="birthdate">Date de naissance du patient:<span class="text-danger"> *</span></label>
            <input type="date" id="birthdate" class="form-control @error('birthdate') is-invalid @enderror" name="birthdate" value="{{ old('birthdate') }}" required>
        </div>
        <div class="col-md-6">
            <label for="lastname" class="mdb-main-label">Nom de famille du patient: <span class="text-danger">*</span></label>
            <select id="lastname" class="form-control @error('lastname') is-invalid @enderror" name="lastname" data-live-search="true" required>
                <option value="" disabled selected>Inscrivez d'abord une date de naissance</option>
                <!-- Generated by Ajax -->
            </select>
        </div>
        <div class="col-md-6">
            <label for="firstname" class="mdb-main-label">Prénom du patient: <span class="text-danger">*</span></label>
            <select id="firstname" class="form-control @error('firstname') is-invalid @enderror" name="firstname" required>
                <option value="" disabled selected>Sélectionnez d'abord le nom de famille du patient</option>
                <!-- Generated by Ajax -->
            </select>
        </div>
        <div class="col-lg-12">
            <label for="title">Titre:<span class="text-danger"> *</span></label>
            <input type="text" id="title" class="form-control @error('title') is-invalid @enderror" name="title" length="150" pattern="(.){5,150}" value="{{ old('title') }}" required>
            @error('title')
            <span class="invalid-feedback">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
        <div class="col">
            <label for="comment">Commentaire:</label>
            <textarea id="comment" name="comment" class="form-control" rows="2">{{ old('description') }}</textarea>
        </div>
    </div>
    <button type="submit" class="btn btn-primary btn-rounded waves-effect mt-5 float-right">Partager</button>
</form>

<script>
// Generate lastnames which matchs with the birthdate
    $(document).ready(function () {
        $('#birthdate').change(function () {
            if ($('#birthdate').val != '') {
                var value = $(this).val();
                $.ajax({
                    url: "/fetchLastname",
                    method: "GET",
                    data: {value: value},
                    success: function (result) {
                        $('#lastname').html(result);
                    }
                })
            }
        });
        $('#lastname').change(function () {
            if ($('#lastname').val != '') {
                var value = $(this).val();
                $.ajax({
                    url: "/fetchFirstname",
                    method: "GET",
                    data: {value: value},
                    success: function (result) {
                        $('#firstname').html(result);
                    }
                })
            }
        });
    });
</script>

@endsection